/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leucotron.rpmanager;

import javax.swing.JFileChooser;

/**
 *
 * @author Augusto
 */
public class JDialogDeploy extends javax.swing.JDialog {

    /**
     * Creates new form JDialogDeploy
     * @param parent
     * @param modal
     */
    public JDialogDeploy(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        rbgRepoOption.add(rbBetaRepo);
        rbgRepoOption.add(rbOfficialRepo);
        this.setTitle("Deploy de RPM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgRepoOption = new javax.swing.ButtonGroup();
        lbRpmName = new java.awt.Label();
        btnSelectRpm = new java.awt.Button();
        btnDeploy = new java.awt.Button();
        rbBetaRepo = new javax.swing.JRadioButton();
        rbOfficialRepo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lbRpmName.setAlignment(java.awt.Label.CENTER);
        lbRpmName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbRpmName.setText("Nenhum arquivo RPM selecionado...");

        btnSelectRpm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSelectRpm.setLabel("Selecionar RPM");
        btnSelectRpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectRpmActionPerformed(evt);
            }
        });

        btnDeploy.setEnabled(false);
        btnDeploy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDeploy.setLabel("Fazer deploy agora!");
        btnDeploy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeployActionPerformed(evt);
            }
        });

        rbBetaRepo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rbBetaRepo.setSelected(true);
        rbBetaRepo.setText("Repositório Beta");

        rbOfficialRepo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rbOfficialRepo.setText("Repositório Oficial");
        rbOfficialRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOfficialRepoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRpmName, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectRpm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbBetaRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(rbOfficialRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnDeploy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelectRpm, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(lbRpmName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBetaRepo)
                    .addComponent(rbOfficialRepo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeploy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectRpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectRpmActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            lbRpmName.setText(fileChooser.getSelectedFile().getName());
            btnDeploy.setEnabled(true);
        }
    }//GEN-LAST:event_btnSelectRpmActionPerformed

    private void btnDeployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeployActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeployActionPerformed

    private void rbOfficialRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOfficialRepoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOfficialRepoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnDeploy;
    private java.awt.Button btnSelectRpm;
    private java.awt.Label lbRpmName;
    private javax.swing.JRadioButton rbBetaRepo;
    private javax.swing.JRadioButton rbOfficialRepo;
    private javax.swing.ButtonGroup rbgRepoOption;
    // End of variables declaration//GEN-END:variables
}
