/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leucotron.rpmanager;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Augusto
 */
public class JDialogGenerator extends javax.swing.JDialog {

    private final String PROP_MODULES_PATH = "app.modulesPath";
    private final String PROPERTIES_PATH = "config.properties";

    /**
     * Creates new form JDialogGenerator
     *
     * @param parent
     * @param modal
     */
    public JDialogGenerator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Gerador de RPM");
        this.lbModulesDir.setText(getModulesDirFromProperties());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        btnRpmGenerate = new java.awt.Button();
        lbModulesDir = new java.awt.Label();
        btnModulesDir = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnRpmGenerate.setActionCommand("");
        btnRpmGenerate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRpmGenerate.setLabel("Gerar RPM");
        btnRpmGenerate.setName(""); // NOI18N
        btnRpmGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRpmGenerateActionPerformed(evt);
            }
        });

        lbModulesDir.setAlignment(java.awt.Label.CENTER);
        lbModulesDir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbModulesDir.setText("Nenhum diretório definido...");

        btnModulesDir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnModulesDir.setLabel("Modificar diretório dos módulos");
        btnModulesDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModulesDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbModulesDir, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModulesDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRpmGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModulesDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbModulesDir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRpmGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRpmGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRpmGenerateActionPerformed

    }//GEN-LAST:event_btnRpmGenerateActionPerformed

    private void btnModulesDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModulesDirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fileChooser.showDialog(this, "Selecionar pasta") == JFileChooser.APPROVE_OPTION) {
            try (OutputStream output = new FileOutputStream(PROPERTIES_PATH)) {
                Properties prop = new Properties();
                prop.setProperty(PROP_MODULES_PATH, fileChooser.getSelectedFile().getAbsolutePath());
                prop.store(output, null);
                lbModulesDir.setText(fileChooser.getSelectedFile().getAbsolutePath());
            } catch (IOException io) {
                Logger.getLogger(JDialogGenerator.class.getName()).log(Level.SEVERE, null, io);
            }
        }
    }//GEN-LAST:event_btnModulesDirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnModulesDir;
    private java.awt.Button btnRpmGenerate;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label lbModulesDir;
    // End of variables declaration//GEN-END:variables

    private String getModulesDirFromProperties() {
        String modulesDir = "Nenhum diretório definido...";
        try (InputStream configProperties = new FileInputStream(PROPERTIES_PATH)) {
            Properties prop = new Properties();
            prop.load(configProperties);
            modulesDir = prop.getProperty(PROP_MODULES_PATH);
        } catch (FileNotFoundException ex) {
            try (OutputStream output = new FileOutputStream(PROPERTIES_PATH)) {
                Properties prop = new Properties();
                prop.setProperty(PROP_MODULES_PATH, modulesDir);
                prop.store(output, null);
            } catch (IOException io) {
                Logger.getLogger(JDialogGenerator.class.getName()).log(Level.SEVERE, null, io);
            }
        } catch (IOException ex) {
            Logger.getLogger(JDialogGenerator.class.getName()).log(Level.SEVERE, null, ex);
        }
        return modulesDir;
    }

}
